version: '3'
services:
  node0:
    build: .
    command: python node.py 0
    ports:
      - "5000:5000"

  node1:
    build: .
    command: python node.py 1
    ports:
      - "5001:5000"

  node2:
    build: .
    command: python node.py 2
    ports:
      - "5002:5000"
